/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconMdiBrightnessAuto: typeof import('~icons/mdi/brightness-auto')['default']
    IconMdiCheckCircleOutline: typeof import('~icons/mdi/check-circle-outline')['default']
    IconMdiCodeJson: typeof import('~icons/mdi/code-json')['default']
    IconMdiContentCopy: typeof import('~icons/mdi/content-copy')['default']
    IconMdiDownloadOutline: typeof import('~icons/mdi/download-outline')['default']
    IconMdiFileDocumentOutline: typeof import('~icons/mdi/file-document-outline')['default']
    IconMdiFolderOpenOutline: typeof import('~icons/mdi/folder-open-outline')['default']
    IconMdiInformationOutline: typeof import('~icons/mdi/information-outline')['default']
    IconMdiLockOpenOutline: typeof import('~icons/mdi/lock-open-outline')['default']
    IconMdiLockOutline: typeof import('~icons/mdi/lock-outline')['default']
    IconMdiMagnify: typeof import('~icons/mdi/magnify')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
    IconMdiOpenInNew: typeof import('~icons/mdi/open-in-new')['default']
    IconMdiRefresh: typeof import('~icons/mdi/refresh')['default']
    IconMdiRestart: typeof import('~icons/mdi/restart')['default']
    IconMdiTextBoxOutline: typeof import('~icons/mdi/text-box-outline')['default']
    IconMdiTranslate: typeof import('~icons/mdi/translate')['default']
    IconMdiZipBoxOutline: typeof import('~icons/mdi/zip-box-outline')['default']
    IconSvgDark: typeof import('~icons/svg/dark')['default']
    IconSvgLight: typeof import('~icons/svg/light')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
